### ISSUE TITLE
Ayuda con error en los Update de dynamicProperties

### ISSUE THREAD

**Issue by rortizgeo** [SIB-Colombia/CESP-GBIF-SiB-VertNet#11]
Hola, en el cojunto de datos que estoy tratando de limpiar con el migrador tengo estos elementos:

Altura total (m)
Diámetro   menor de la copa (m)
Diámetro mayor de la copa (m)
Cobertura total (m)

Los quiero poner en las dynamicProperties pero en las consultas Update existentes no hay casos para estas medidas por lo que asumí que podía modificar las primeras cambiando el contenido de la consulta de la siguiente manera:

SiInm(EsNulo([Campo76]),"{"+'"'+"Diámetro mayor de la copa en metros"+'"'+":"+'"'+[Campo76]+'"',[Campo76]+", "+'"'+"Diámetro mayor de la copa en metros"+'"'+":"+'"'+[Campo76]+'"')

Donde "Campo 76 corresponde a la columna con el valor del diámetro menor de la copa". Modifiqué varios Update (los 4 primeros) cambiando cada uno por la respectiva propiedad del conjunto de datos que estoy probando, en el primer update no genera error, en los demás si.

Update dynamicProperties for BandNumber, Hoja de datos, Modificar

Si me pueden colaborar explicandome cual es el error y como lo arreglo

Gracias!

**Comment by pzermoglio** [comment]
@rortizgeo 
Hola Ricardo,

Veo un problema en que estás agregando los datos al campo 76, y no al campo dynamicProperties. Si te fijás en la consulta original, es más o menos así:

![image](https://user-images.githubusercontent.com/9394433/31017426-c9e5cde6-a4fe-11e7-9428-d4c0a926b9a7.png)

Ahí marqué en rojo la condición del IIf, en azul la primera cláusula y en verde la segunda cláusula.

Es decir, lo que hace es: 
Si el campo dynamicProperties no tiene nada, adicionar: {"Campo 76": "[Campo 76]"
Si el campo dynamicProperties ya tiene algo, dejar lo que estaba y adicionar a eso el campo 76.

Fijate que la expresión abre una estructura JSON, con { y luego pone la clave y el valor entre comillas, un ejemplo sería: {"altura total":"30m"
Luego, fijate que no cierra el JSON, eso es porque luego hay otro query. que está activado en el macro por default, que lo cierra.

Luego, respecto de modificar los queries ya exitentes, podés hacerlo así, usando uno que ya esté y modificarlo, pero si lo renombrás, acordate de cambiar el nombre también en el macro, porque si no lo cambiás ahí también no lo vas a poder activar.
Lo que podés hacer, alternativamente, es agregar queries, con copy-paste de alguno que ya esté, básicamente, pero para no perder ninguno. Tendrías que copiar alguno de los queries y modificar la copia, y luego copiar las líneas correspondientes en el macro también y modificarlas.

Espero que esto ayude! :)
Abrazo

**Comment by rortizgeo** [comment]
Hola Paula!

Gracias, efectivamente estaba haciendo mal la consulta, ayer la corregí, sin embargo no tenía la certeza de estar haciendola bien  pero con la explicación ya me queda claro. Finalmente el problema es que siempre se me olvida eliminar las columnas dentro de los update que no mapean a nada, o porque no se si son parte de la consulta no las tocó


![captura3](https://user-images.githubusercontent.com/31864538/31022743-56775cd4-a4ff-11e7-9e70-e691ea4e6966.PNG)


Gracias!

**Comment by pzermoglio** [comment]
@rortizgeo 
Genial :)
Sí, ojo con los criterios también, especialmente cuando copiás-pegás un query, muy probablemente los criterios no apliquen a una dynamicProperty diferente; los podés borrar directamente o cambiar por algún criterio que tenga sentido para el campo correspondiente.

**Comment by pzermoglio** [comment]
Quizás sea bueno incorporar algo de esto en la documentación. Etiqueto este issue y lo cierro, pero miraré luego todos los issues, abiertos y cerrados, para incorporar en la documentación.
