### ISSUE TITLE
Columnas en el SimpleDwC no están en el SimpleDwCforIPT

### ISSUE THREAD

**Issue by rortizgeo** [SIB-Colombia/CESP-GBIF-SiB-VertNet#15]
Hola!

Luego de correr el 1c-RunAgregators. revisé el SimpleDwCforIPT y verifique que dos columnas que cree a partir del samplingProtocol (sampleSizeValue y sampleSizeUnit) se crearon en el PlanstDwC2 del folder workspace pero no aparecen el archivo listo para el IPT. Adjunto las imágenes

![captura7samplesimpledwc](https://user-images.githubusercontent.com/31864538/31185852-ab28afac-a8f2-11e7-8a0b-8ce8e9bb4a8f.PNG)

Y en la siguiente imagen que es el excel resultante del SimpleDwCforIPT no están

![captura6sample](https://user-images.githubusercontent.com/31864538/31185853-ac34500e-a8f2-11e7-8858-a7c6b18f1ef6.PNG)

Gracias! quedo atento para saber donde cometí el error

R.

**Comment by tucotuco** [comment]
Tuviste razón. Agregué los campos a la consulta SimpleDwCForIPTquery en commit 4df57597cf615baf513f46827749239a97d7670c del toolkit.
