### ISSUE TITLE
Problema con LegacyCoordinates 

### ISSUE THREAD

**Issue by rortizgeo** [SIB-Colombia/CESP-GBIF-SiB-VertNet#16]
Hola, 

En el conjunto de datos que estoy probando tengo las coordenadas como se ve a continuación. 

![captura10_verbatimcoordinatessource](https://user-images.githubusercontent.com/31864538/31186389-19e004e4-a8f4-11e7-9440-56915a30e9e3.PNG)

En el primer mapeo de source, cruce los elementos decimalLatitud y decimalLongitud, todo lo demás lo dejé para el Legacy el cual se mapeo de la siguiente manera.

![captura8_verbatimcoordinateslegacy](https://user-images.githubusercontent.com/31864538/31186321-f0546e94-a8f3-11e7-975e-cc30ebf09282.PNG)

Sin embargo en el simpleDwC no logro obtener las verbatimCoordinates en GMS.

![captura9_verbatimcoordinatessimpledwc](https://user-images.githubusercontent.com/31864538/31186509-73347778-a8f4-11e7-9d49-14fb2d8e910a.PNG)

No encuentro donde pude cometer algún error, ojalá me puedan ayudar, Gracias.

**Comment by pzermoglio** [comment]
@rortizgeo 

El migrador no tiene una función que arme el verbatimCoordinates automáticamente a partir de otros campos, tendrías que construirlo. Lo podés hacer armando primero verbatimLatitude y verbatimLongitude y luego concatenando en verbatimCoordinates, o directamente en verbatimCoordinates (pero te va a quedar una expresión larguísima si lo hacés directamente en este campo). Ambos pueden hacerse directamente en el mapeo inicial, poniendo una expresión en el campo correspondiente que te concatene los campos originales en GMS de la tabla Specimens. Tenés que tener en cuenta los valores nulos, vas a tener que usar un Iff null... etc. 
La expresión sería como sigue:

Si A es la latitud en grados, B en minutos y C en segundos:

![image](https://user-images.githubusercontent.com/9394433/31401448-437b37fe-adc9-11e7-9174-b4dee308a45e.png)

La expresión del medio (los Iffs) concatena A, B y C. El Reemplazar evita que aparezcan espacios en blanco en los casos en que alguno de los campos esté vacío (fijate que la parte "  "," " lo primero que está entre comillas es un doble espacio y lo segundo es un espacio solo, para los casos en que dos campos o un campo esté vacío, respectivamente). Luego, el Recortar te evita espacios extra al principio y final de la expresión.

Una vez que tenés armada esta expresión para latitud y longitud verbatim, podés simplemente concatenarlas en verbatimCoordinates.

Abrazo!

**Comment by rortizgeo** [comment]
Funciono Perfecto!, gracias

Le agregué a la expresión las notaciones para coordenadas en GMS, quedó así

Recortar(Reemplazar(SiInm(EsNulo([A]),"",[A])+"°"+SiInm(EsNulo([B]),"",[B])+"'"+SiInm(EsNulo([C]),"",[C]+"'' "),"  "," "))

**Comment by pzermoglio** [comment]
Fenómeno :)
Closing this issue.
