### ISSUE TITLE
Duda con los reportes

### ISSUE THREAD

**Issue by rortizgeo** [SIB-Colombia/CESP-GBIF-SiB-VertNet#18]
Hola!

En el paso 35 corrí el 1c-RunAgregators, aparecen los reportes en formato .csv, no entiendo según la documentación si deben aparecer así o en un .txt, me genera la duda porque alcancé a leer estos errores en la consola y adicionalmente algunos reportes están vacíos, les envío un pantallazo.  

![image](https://user-images.githubusercontent.com/31864538/31189168-e343cdcc-a8fc-11e7-8da6-e74366229612.png)

Gracias!

**Comment by pzermoglio** [comment]
@rortizgeo 
Los reportes se generan como .csv (antes eran txt), así que eso está bien.
Los reportes vacíos también están bien, corresponden a tests donde no se encontraron errores. Es decir, si los datos fueran perfectos, todos los reportes deberían aparacer vacíos (sin registros asociados).

**Comment by rortizgeo** [comment]
Ok, ya entiendo, pensé que el migrador generaba el reporte solo en caso de que estuviera prendido ese macro, es decir, en mi caso no tengo coordinateUncertainty, y ese Legacy y demás consultas están apagadas, sin embargo se genera el reporte que está vacío. Creí que era un error. 

Es decir, en caso de querer enviarle un reporte de errores a una colección tengo que ver cuales efectivamente están llenos, para no generar confusiones en el publicador

**Comment by pzermoglio** [comment]
@rortizgeo 
En VertNet directamente mandamos todos los reportes, no hacemos una selección. Esto me parece la mejor opción, porque entonces los publicadores pueden estar seguros de que NO se encontraron errores para las características analizadas en los reportes que aparecen vacíos. Lo que sí hay que explicarles a los publicadores cuando se envían los reportes es que pueden haber algunos vacíos y que eso no es un error, sino justamente algo positivo :)

Closing this issue.
