### ISSUE TITLE
Acceso Admin al repositorio GH

### ISSUE THREAD

**Issue by pzermoglio** [SIB-Colombia/CESP-GBIF-SiB-VertNet#2]
@leobuitrago @daiesco 
Necesitaría acceso de administrador a este repositorio para poder agregar etiquetas y organizar los issues. Habrá posibilidad de tenerlo? Gracias!

**Comment by leobuitrago** [comment]
Listo Paula, ya estas habilitada como Admin https://github.com/SIB-Colombia/CESP-GBIF-SiB-VertNet/invitations

Saludos!

**Comment by pzermoglio** [comment]
Gracias Leo!
