### ISSUE TITLE
Error en prueba con el migrador

### ISSUE THREAD

**Issue by rortizgeo** [SIB-Colombia/CESP-GBIF-SiB-VertNet#3]
Hola!, estoy atorado en este error, no encuentro la manera de solucionarlo

Reporte de error en prueba con el migrador luego de correr el 1a-RunMigrators.bat

2, Report - coordinatePrecision not numeric Export Specification, Report - coordinatePrecision not numeric, C:\tempvertnetprocessing\reports\Report - coordinatePrecision not numeric.txt, Sí, , 6500

![captura1](https://user-images.githubusercontent.com/31864538/30594466-c5f01248-9d13-11e7-85fe-4fbac1e85a52.PNG)

Gracias!

**Comment by leobuitrago** [comment]
@tucotuco nos puedes ayudar a resolver esto?. Mil gracias John!

**Comment by pzermoglio** [comment]
Hola Ricardo,
John se encontró con ese error ayer. Ya lo arregló, pero está haciendo unas modificaciones más al migrador. Va a subir una nueva versión pronto. Te avisamos cuando esté lista así la podés bajar nuevamente de https://github.com/VertNet/toolkit con los errores solucionados.
Abrazo

**Comment by pzermoglio** [comment]
El nuevo migrador ya está disponible. Se puede bajar de: https://github.com/VertNet/toolkit
John y Dave están pasando por el nuevo proceso y modificando la documentación en concordancia.
