### ISSUE TITLE
Pruebas migrador

### ISSUE THREAD

**Issue by rortizgeo** [SIB-Colombia/CESP-GBIF-SiB-VertNet#4]
Hola Paula, aprovecho para dejarte unas observaciones que tuve estos días al probar el migrador y que quizás aporten a la documentación.

Muchos de los errores que cometí haciendo la prueba con el migrador ocurren en el Step 22. en los Legacy, creo que es positivo si se agregan unos ejemplos o pasos para los Legacy mas comunes que creo que son el de coordenadas y fechas

En ocasiones tengo dudas sobre como llenar los elementos verbatim en el mapeo, porque desconozco los procesos de limpieza que hace el migrador. Depronto una lista de los tipos de limpieza que hace el migrador ayude a comprender el panorama. Por ejemplo; Fecha: El eventDate mapeado se convierte al estandar aaaa-m-dd, llena los elementos year, month y day del DwC y guarda la fecha original (verbatim)

Ojalá te sirva

Saludos!

**Comment by pzermoglio** [comment]
Hola Ricardo,

Siii! Sirven mucho tus comentarios. Voy a armar dos issues separados para esos tópicos para acordarme de incluirlos en la documentación. Justamente ahora John y Dave están pasando por el migrador y agregando comentarios/modificaciones al documento de los pasos.

Cierro entonces este issue y abro otros dos.

Un abrazo
