### ISSUE TITLE
Proposed changes to VertNet Migrator Toolkit: Instructions for basic use

### ISSUE THREAD

**Issue by tucotuco** [SIB-Colombia/CESP-GBIF-SiB-VertNet#7]
Dave Bloom and I went through the document in the process of customizing a new migrator using the 2017-09-20 version. Comments and suggested changes based on how the new migrator works were added. These need to be incorporated before translation. @pzermoglio will do this.

**Comment by pzermoglio** [comment]
Document has been reviewed and changes incorporated. There remain a couple of comments open in the document, mostly concerning extra documentation needed.
Closing this issue.
