### ISSUE TITLE
Recomendación para la documentación del paso 16

### ISSUE THREAD

**Issue by rortizgeo** [SIB-Colombia/CESP-GBIF-SiB-VertNet#9]
Hola, 

En el documento EN_PRELIM_VertNet Migrator Toolkit - Detailed instructions, donde están los comentarios de John y David, creo que es necesario en el paso 16 indicar que la tabla "LookupCollectionMetadata" se debe modificar dentro del template DwC2ExtractTemplate-XXX, quizás sea evidente pero según los cambios que se deben hacer en los pasos y el nuevo template de Source, puede ser confuso.

Adicionalmente, se indica que si la fuente tiene varias opciones en el basisOfRecord mezcladas, el procedimiento cambia y se debe mapear de otra manera, pero creo que no se específica, me gustaría saber que hacer en ese caso, o si ese es uno de los posibles usos de los filtros en el paso 17 quizás deba agregarse como una posible opción de uso de los filtros

Saludos!, espero sea de utilidad

**Comment by pzermoglio** [comment]
@rortizgeo 
Hola Ricardo,
Gracias por el comentario. Voy a poner una nota en el documento para capturar esto.
Aún tengo que revisar el documento para integrar los comentarios de John y Dave, lo haré la próxima semana (armo un issue para eso).

**Comment by pzermoglio** [comment]
Cierro este issue, pero miraré luego todos los issues, abiertos y cerrados, para incorporar en la documentación.
